version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - aws --version
      - java --version
      - pip install awscli --upgrade --user
      - echo Logging in to Amazon ECR...
      - echo $(aws ecr get-login-password)|docker login --password-stdin --username AWS 634182598822.dkr.ecr.eu-west-2.amazonaws.com
      - aws --version
      - echo Logging in to Docker Hub...
      - echo Passw0rd1 | docker login --username llanterme --password-stdin
      - REPOSITORY_URI=634182598822.dkr.ecr.eu-west-2.amazonaws.com/event-publisher-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - mvn clean
      - mvn install
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"event-publisher-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json